source {{prezto}}/runcoms/zprofile
source {{salted}}/envvar.zsh

[[ -e {{salted}}/zprofile ]] && source {{salted}}/zprofile

export fpath=($fpath {{salted}}/completions)

. /usr/local/miniconda3/etc/profile.d/conda.sh
